### ISSUE TITLE
gitk-light3 tweaks

### ISSUE THREAD

**Issue by ianchanning** [sudorook/colorific.vim#2]
Hi there,

Sorry I should do this as a PR, if I remember I will. I've been doing a [deep dive on superuser into making gitk prettier](https://superuser.com/questions/30175/gitk-looks-ugly-doesnt-honor-theme-settings/1707378#1707378), and I used your [gitk-light3](https://github.com/sudorook/colorific.vim/blob/master/git/gitk-light3) theme, however I made some slight tweaks, here below is what I have changed with comments.

This is what I get at the end:

![Screenshot from 2022-03-02 13-39-07](https://user-images.githubusercontent.com/233318/156363560-a5dcead6-e612-429d-9fda-da06aecc5680.png)

I'm using the [yaru tk theme](https://github.com/TkinterEP/ttkthemes/tree/master/ttkthemes/png/yaru) with Pop OS.

A couple of things I noticed:

* Your `uifgdisabledcolor` for the light themes is a dark purple that doesn't seem to match - I replaced it with a light grey
* It's hard to tell the difference between the 3 light themes - when comparing screenshots I noticed the slight difference in the `uicolor` for which the light3 theme best matched the yaru theme
* I preferred the GitHub style `diffbgcolors`
* You're including other settings other than the colours setting in your configs - I think its better to leave them out (except for the `want_ttk` which affects the colours).

```sh
set uicolor #f5f6f7
set want_ttk 1
set bgcolor #ffffff
set fgcolor #5c616c
set uifgcolor #5c616c
set uifgdisabledcolor #d3dae3
set colors {#00d96f #e34f4c #73c2e6 #ff79c6 #f8f8f8 #ffb86c #ffb86c}
set diffcolors {{#5c616c} #5c616c #73c2e6}
set mergecolors {#e34f4c #73c2e6 #00d96f #73c2e6 #ffb86c #8be9fd #ff79c6 #f1fa8c #8be9fd #ff79c6 #8be9fd #ffb86c #8be9fd #00d96f #ffb86c #ff79c6}
set markbgcolor #ffffff
set diffcontext 3
set selectbgcolor #e7e8eb
set foundbgcolor #f1fa8c
set currentsearchhitbgcolor #ffb86c
set extdifftool meld
set perfile_attrs 0
set headbgcolor #00d96f
set headfgcolor black
set headoutlinecolor #5c616c
set remotebgcolor #ffb86c
set tagbgcolor #f1fa8c
set tagfgcolor black
set tagoutlinecolor #5c616c
set reflinecolor #5c616c
set filesepbgcolor #f5f6f7
set filesepfgcolor #5c616c
set linehoverbgcolor #f1fa8c
set linehoverfgcolor black
set linehoveroutlinecolor #5c616c
set mainheadcirclecolor #f1fa8c
set workingfilescirclecolor #e34f4c
set indexcirclecolor #00d96f
set circlecolors {#ffffff #73c2e6 #f5f6f7 #73c2e6 #73c2e6}
set linkfgcolor #73c2e6
set circleoutlinecolor #f5f6f7
set diffbgcolors {{#ffd7d5} #e6ffec}
```

**Comment by sudorook** [comment]
I'm looking into this. First, in response to your issue / pull request:

> Your uifgdisabledcolor for the light themes is a dark purple that doesn't
> seem to match - I replaced it with a light grey

Good catch. I'll replace them with the comment color from each Vim theme.

> It's hard to tell the difference between the 3 light themes - when comparing
> screenshots I noticed the slight difference in the uicolor for which the
> light3 theme best matched the yaru theme

I select the background and foreground colors based on the GTK themes I'm
trying to match. The light themes often use #fff as the background color, so
all the light gitk themes end up looking pretty similar. The main differences
are the off-white UI colors and the foreground colors.

> I preferred the GitHub style diffbgcolors

I could reduce the saturation and also brighten the background colors... I 
saw your recent pull request. It does look better.

> You're including other settings other than the colours setting in your
> configs - I think its better to leave them out (except for the `want_ttk`
> which affects the colours).

The extra settings are the default values for gitk. If I don't set all of them
directly in the config file, they will be written to the gitk config file
whenever the gitk program is closed.

I may as well set fewer options, but some, like the fonts, I will keep in. I'm
going for consistency with the GTK themes. The font families and font 
sizes are hard-coded in the shell themes, so they are hard-coded to match 
(roughly) here, too.
__________

I've been looking into why `want_ttk=1` doesn't load themes properly. Turns out 
it's because gitk never applies the config colors to any `ttk::style` properties.

For getting proper gitk theming support, I can think of two options:

## 1. Submitting an upstream patch to gitk.

Adding the following to the the `setui` function gets most of the way there:
```
set have_ttk [llength [info commands ::ttk::style]]
if {$have_ttk} {
    ttk::style configure . \
      -background $c \
      -selectfg $selc \
      -troughcolor $c
    ttk::style map TCombobox -fieldbackground [list disabled $c readonly $c]
    ttk::style map TButton -background [list disabled $c readonly $c]
    ttk::style map TScrollbar -background [list disabled $c readonly $c]
}
```

This end up looking like:
![gitk_ttk_fix](https://user-images.githubusercontent.com/6200846/156794302-299f178a-5285-43de-b9c0-5ec1022ccc8b.png)

## 2. Compiling a ttk theme along with various GTK themes.

Fortunately, there are a bunch of existing ttk themes aiming to mimic various
GTK themes, including adapta, arc, yaru, etc. Installing the arc ttk theme and
forcing gitk to load it yields:
![arc-tcl-theme](https://user-images.githubusercontent.com/6200846/156794326-2490bea5-bba1-46ea-be94-28478f31c9a0.png)

The UI is much more sluggish to load, though, and setting it up is more of a
hassle. It still requires colors to be set via the gitk config because the ttk 
items are hard-coded to the default colors.

**Comment by ianchanning** [comment]
> The extra settings are the default values for gitk. If I don't set all of them directly in the config file, they will be written to the gitk config file whenever the gitk program is closed.
> 
> I may as well set fewer options, but some, like the fonts, I will keep in. I'm going for consistency with the GTK themes. The font families and font sizes are hard-coded in the shell themes, so they are hard-coded to match (roughly) here, too.

Ah ok fair enough. For the rest thank you for looking into this!

**Comment by ianchanning** [comment]
I'd say this issue is closed, I just wanted to let you that I'd been making use of your lovely themes!
